class DogHousesController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :render_not_found_response

  def index
    render json: DogHouse.all
  end


  #GET /dog_houses/:id
  def show
    dog_house = DogHouse.find(params[:id])
    render json: dog_house, include: :reviews #This a specification that we want the dog house and its reviews and is made possible by the fact that one dog_house has many reviews
    #Adding the include option will call the instance methods generated by the macro for the assocaited table hence return the associated records.
    #This refers to nesting of a has_many association since once instance has many of the included
    #This is further called serialization and happens when we are converting our hash to Json
  end

  private

  def render_not_found_response
    render json: { error: "Dog house not found" }, status: :not_found
  end

end
